services:
  - type: web
    name: ev-backend
    env: node
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    envVars:
      - key: NODE_VERSION
        value: "18"
